/**
 * 简体中文语言包
 */

export default {
  // 通用
  "app_name": "Ada&Ava Desktop for Chrome",
  "ok": "确定",
  "cancel": "取消",
  "save": "保存",
  "delete": "删除",
  "edit": "编辑",
  "add": "添加",
  "search": "搜索",
  "loading": "加载中...",
  "error": "错误",
  "success": "成功",
  
  // 时间和日期
  "today": "今天",
  "yesterday": "昨天",
  "tomorrow": "明天",
  "monday": "星期一",
  "tuesday": "星期二",
  "wednesday": "星期三",
  "thursday": "星期四",
  "friday": "星期五",
  "saturday": "星期六",
  "sunday": "星期日",
  "january": "1月",
  "february": "2月",
  "march": "3月",
  "april": "4月",
  "may": "5月",
  "june": "6月",
  "july": "7月",
  "august": "8月",
  "september": "9月",
  "october": "10月",
  "november": "11月",
  "december": "12月",
  
  // 界面元素
  "new_tab": "新标签页",
  "edit_mode": "编辑模式",
  "exit_edit_mode": "退出编辑模式",
  "edit_shortcuts": "编辑快捷方式",
  "edit_cities": "编辑城市列表",
  "edit_shortcut": "编辑快捷方式",
  "add_shortcut": "添加快捷方式",
  "shortcut_name": "名称",
  "shortcut_url": "网址",
  "shortcut_url_with_index": "网址{index}",
  "shortcut_icon": "图标",
  "shortcut_icon_placeholder": "输入完整URL (例如: https://example.com/icon.png)",
  "add_url": "添加网址",
  "remove_url": "移除网址",
  "export_data": "导出数据",
  "import_data": "导入数据",
  "confirm_delete": "确定要删除吗？",
  "confirm_delete_shortcut": "确定要删除此快捷方式吗？",
  
  // 城市和天气
  "add_city": "添加城市",
  "edit_city_list": "编辑城市列表",
  "enter_city_name": "输入城市名称",
  "search_city": "搜索城市...",
  "city_search_results": "搜索结果",
  "no_results": "没有找到结果",
  "custom_city": "自定义城市",
  "custom_city_name": "城市名称",
  "timezone": "时区",
  "select_timezone": "选择时区",
  
  // 时间格式
  "time_format": "时间格式",
  "12_hour_format": "12小时制 (上午/下午)",
  "24_hour_format": "24小时制",
  "time_format_description": "选择您喜欢的时间显示格式",
  "custom_time_format": "自定义时间格式",
  "custom_date_format": "自定义日期格式",
  "date_format_1": "年-月-日 (2023-01-31)",
  "date_format_2": "月/日/年 (01/31/2023)",
  "date_format_3": "日/月/年 (31/01/2023)",
  "date_format_4": "中文格式 (2023年01月31日)",
  
  // 日期格式
  "date_format_title": "自定义日期格式",
  "date_format_ymd": "年-月-日 (2023-01-31)",
  "date_format_mdy": "月/日/年 (01/31/2023)",
  "date_format_dmy": "日/月/年 (31/01/2023)",
  "date_format_chinese": "中文格式 (2023年01月31日)",
  "date_format_english": "英文格式 (Jan 31, 2023)",
  "date_format_european": "欧洲格式 (31 Jan 2023)",
  "date_format_updated": "日期格式已更新",
  "date_format_save_error": "保存日期格式失败",
  
  // 设置
  "settings": "设置",
  "language": "语言",
  "language_zh_cn": "简体中文",
  "language_zh_tw": "繁体中文",
  "language_en": "English",
  "background": "背景",
  "select_background": "选择背景图片",
  "upload_background": "上传背景图片",
  "reset_background": "重置背景",
  
  // 通知和消息
  "data_exported": "数据已导出",
  "data_imported": "数据已导入",
  "import_error": "导入错误",
  "invalid_data": "无效的数据格式",
  "background_updated": "背景已更新",
  "language_updated": "语言已更新",
  "settings_saved": "设置已保存",
  "edit_mode_entered": "已进入编辑模式",
  "edit_mode_exited": "已退出编辑模式",
  "shortcut_updated": "快捷方式已更新",
  "shortcut_added": "快捷方式已添加",
  "shortcut_deleted": "快捷方式已删除",
  "please_enter_name": "请输入名称",
  "please_enter_url": "请至少输入一个网址",
  "app_init_error": "初始化应用程序时出错: {error}",
  "switched_to_24h": "已切换到24小时制",
  "switched_to_12h": "已切换到12小时制",
  "time_format_switch_error": "切换时间格式失败",
  "data_export_error": "导出数据时出错",
  "data_import_error": "导入数据失败",
  
  // 其他
  "support_developer": "支持开发者",

  // 图标相关
  "upload_icon": "上传图标",
  "enter_icon_url": "输入图标URL",
  "use_default_icon": "使用默认",
  "icon_load_failed": "图标加载失败",
  "icon_loaded_successfully": "图标加载成功",
  "loading_icon": "正在加载图标...",
  "invalid_image_file": "无效的图片文件",
  "icon_upload_failed": "图标上传失败",
  "icon_reset_to_default": "图标已重设",
  "invalid_url": "无效的URL",
  "icon_url_placeholder": "请输入图标的URL地址",
  
  // 图片编辑器相关
  "image_editor_title": "图片编辑器",
  "enter_image_url": "输入图片网址",
  "upload_image": "打开本地图片",
  "image_url_placeholder": "请输入图片的URL地址",
  "load_image": "加载图片",
  "background_color": "背景颜色:",
  "pick_color": "选择颜色",
  "editor_instruction_1": "1. 拖动选择框到合适位置",
  "editor_instruction_2": "2. 调整选择框大小",
  "editor_instruction_3": "3. 点击吸管选择背景色",
  "apply": "应用",
  "image_processing": "正在处理图片...",
  "image_processed": "图片处理完成",
  "image_process_success": "图片处理成功",
  "image_process_failed": "图片处理失败",
  "no_image_loaded": "请先加载图片",
  "invalid_image": "无效的图片",
  "selection_too_small": "选择区域太小",
  "cors_error": "由于跨域限制无法加载图片，请尝试保存图片后手动上传",
  "color_selected": "已选择颜色",
  "color_pick_failed": "选择颜色失败",
  "editor_open_failed": "打开图片编辑器失败",
  "transparent_background_detected": "检测到图片已有透明背景，是否直接使用？",
  "continue_edit": "继续编辑",
  "use_as_is": "直接使用",
  "image_used_as_is": "已直接使用原图",
  "element_not_found": "找不到页面元素，请刷新页面重试",
  "image_load_failed": "图片加载到Canvas失败",
  "form_submit_error": "提交表单时出错，请重试",
  "icon_hint": "双击图标可编辑",
  "url_required": "请填写此字段",
  "url_empty_or_fill": "输入网址，或者留空",
  "reset_icon": "重设图标"
}; 