/**
 * 繁體中文語言包
 */

export default {
  // 通用
  "app_name": "Ada&Ava Desktop for Chrome",
  "ok": "確定",
  "cancel": "取消",
  "save": "保存",
  "delete": "刪除",
  "edit": "編輯",
  "add": "添加",
  "search": "搜索",
  "loading": "加載中...",
  "error": "錯誤",
  "success": "成功",
  
  // 時間和日期
  "today": "今天",
  "yesterday": "昨天",
  "tomorrow": "明天",
  "monday": "星期一",
  "tuesday": "星期二",
  "wednesday": "星期三",
  "thursday": "星期四",
  "friday": "星期五",
  "saturday": "星期六",
  "sunday": "星期日",
  "january": "1月",
  "february": "2月",
  "march": "3月",
  "april": "4月",
  "may": "5月",
  "june": "6月",
  "july": "7月",
  "august": "8月",
  "september": "9月",
  "october": "10月",
  "november": "11月",
  "december": "12月",
  
  // 界面元素
  "new_tab": "新標籤頁",
  "edit_mode": "編輯模式",
  "exit_edit_mode": "退出編輯模式",
  "edit_shortcuts": "編輯快捷方式",
  "edit_cities": "編輯城市列表",
  "edit_shortcut": "編輯快捷方式",
  "add_shortcut": "添加快捷方式",
  "shortcut_name": "名稱",
  "shortcut_url": "網址",
  "shortcut_url_with_index": "網址{index}",
  "shortcut_icon": "圖標",
  "shortcut_icon_placeholder": "輸入完整URL (例如: https://example.com/icon.png)",
  "add_url": "添加網址",
  "remove_url": "移除網址",
  "export_data": "導出數據",
  "import_data": "導入數據",
  "confirm_delete": "確定要刪除嗎？",
  "confirm_delete_shortcut": "確定要刪除此快捷方式嗎？",
  
  // 城市和天氣
  "add_city": "添加城市",
  "edit_city_list": "編輯城市列表",
  "enter_city_name": "輸入城市名稱",
  "search_city": "搜索城市...",
  "city_search_results": "搜索結果",
  "no_results": "沒有找到結果",
  "custom_city": "自定義城市",
  "custom_city_name": "城市名稱",
  "timezone": "時區",
  "select_timezone": "選擇時區",
  
  // 時間格式
  "time_format": "時間格式",
  "12_hour_format": "12小時制 (上午/下午)",
  "24_hour_format": "24小時制",
  "time_format_description": "選擇您喜歡的時間顯示格式",
  "custom_time_format": "自定義時間格式",
  "custom_date_format": "自定義日期格式",
  "date_format_1": "年-月-日 (2023-01-31)",
  "date_format_2": "月/日/年 (01/31/2023)",
  "date_format_3": "日/月/年 (31/01/2023)",
  "date_format_4": "中文格式 (2023年01月31日)",
  
  // 日期格式
  "date_format_title": "自定義日期格式",
  "date_format_ymd": "年-月-日 (2023-01-31)",
  "date_format_mdy": "月/日/年 (01/31/2023)",
  "date_format_dmy": "日/月/年 (31/01/2023)",
  "date_format_chinese": "中文格式 (2023年01月31日)",
  "date_format_english": "英文格式 (Jan 31, 2023)",
  "date_format_european": "歐洲格式 (31 Jan 2023)",
  "date_format_updated": "日期格式已更新",
  "date_format_save_error": "保存日期格式失敗",
  
  // 設置
  "settings": "設置",
  "language": "語言",
  "language_zh_cn": "簡體中文",
  "language_zh_tw": "繁體中文",
  "language_en": "English",
  "background": "背景",
  "select_background": "選擇背景圖片",
  "upload_background": "上傳背景圖片",
  "reset_background": "重置背景",
  
  // 通知和消息
  "data_exported": "數據已導出",
  "data_imported": "數據已導入",
  "import_error": "導入錯誤",
  "invalid_data": "無效的數據格式",
  "background_updated": "背景已更新",
  "language_updated": "語言已更新",
  "settings_saved": "設置已保存",
  "edit_mode_entered": "已進入編輯模式",
  "edit_mode_exited": "已退出編輯模式",
  "shortcut_updated": "快捷方式已更新",
  "shortcut_added": "快捷方式已添加",
  "shortcut_deleted": "快捷方式已刪除",
  "please_enter_name": "請輸入名稱",
  "please_enter_url": "請至少輸入一個網址",
  "app_init_error": "初始化應用程序時出錯: {error}",
  "switched_to_24h": "已切換到24小時制",
  "switched_to_12h": "已切換到12小時制",
  "time_format_switch_error": "切換時間格式失敗",
  "data_export_error": "導出數據時出錯",
  "data_import_error": "導入數據失敗",
  
  // 其他
  "support_developer": "支持開發者",
  
  // 圖標相關
  "upload_icon": "上傳圖標",
  "enter_icon_url": "輸入圖標URL",
  "use_default_icon": "使用預設",
  "icon_load_failed": "圖標載入失敗",
  "icon_loaded_successfully": "圖標載入成功",
  "loading_icon": "正在載入圖標...",
  "invalid_image_file": "無效的圖片檔案",
  "icon_upload_failed": "圖標上傳失敗",
  "icon_reset_to_default": "圖標已重設",
  "invalid_url": "無效的URL",
  "icon_url_placeholder": "請輸入圖標的URL地址",
  "reset_icon": "重設圖標",
  
  // 圖片編輯器相關
  "image_editor_title": "圖片編輯器",
  "enter_image_url": "輸入圖片網址",
  "upload_image": "開啟本地圖片",
  "image_url_placeholder": "請輸入圖片的URL地址",
  "load_image": "載入圖片",
  "background_color": "背景顏色:",
  "pick_color": "選擇顏色",
  "editor_instruction_1": "1. 拖動選擇框到合適位置",
  "editor_instruction_2": "2. 調整選擇框大小",
  "editor_instruction_3": "3. 點擊吸管選擇背景色",
  "apply": "應用",
  "image_processing": "正在處理圖片...",
  "image_processed": "圖片處理完成",
  "image_process_success": "圖片處理成功",
  "image_process_failed": "圖片處理失敗",
  "no_image_loaded": "請先載入圖片",
  "invalid_image": "無效的圖片",
  "selection_too_small": "選擇區域太小",
  "cors_error": "由於跨域限制無法載入圖片，請嘗試保存圖片後手動上傳",
  "color_selected": "已選擇顏色",
  "color_pick_failed": "選擇顏色失敗",
  "editor_open_failed": "開啟圖片編輯器失敗",
  "transparent_background_detected": "檢測到圖片已有透明背景，是否直接使用？",
  "continue_edit": "繼續編輯",
  "use_as_is": "直接使用",
  "image_used_as_is": "已直接使用原圖",
  "element_not_found": "找不到頁面元素，請刷新頁面重試",
  "image_load_failed": "圖片載入到Canvas失敗",
  "form_submit_error": "提交表單時出錯，請重試",
  "icon_hint": "雙擊圖標可編輯",
  "url_required": "請填寫此欄位",
  "url_empty_or_fill": "輸入網址，或者留空",
  
  // 背景圖片編輯器
  "apply": "應用"
}; 
